### ISSUE TITLE
Support git describe-like features

### ISSUE THREAD

**Issue by drekbour** [qoomon/maven-git-versioning-extension#101]
Despite being tagged with `git describe`, this (wonderful!) plugin cannot be configured to work with it! `Describe` gives a human-readable name based on the "nearest tag". Similar work for comparison : https://github.com/palantir/gradle-git-version

This would be used something like

    <versionFormat>${describe}${dirty}</versionFormat>

which resolves using

        git describe --tags --always --first-parent

If you intend definitively not to support it then at least this issue can clarify that as I won't be the last to ask. I don't see much difference in repeatability between tags and branches, they are all git references that can be rewritten!

I could probably PR this change if I know it will be accepted.

**Comment by qoomon** [comment]
Hi @drekbour in general I'm against having this feature. However I'd like to provide separate placeholders for the different parts of git describe (last version tag name and distance to last version tag).

I'd more than happy to accept a PR. 

Would be great to have something like following placeholders, if possible
* `${tag. recent}`
* `${tag. recent.distance}`

And following options in config file
* `<tagPattern>` to filter tags for git describe

Edge Cases to consider
* shallow cloned repository
* no tag found

**Comment by drekbour** [comment]
The pre-canned `git describe` (which is more than the sum of it's parts because there is some _logic_ applied in there too) is still a valid choice used by many! Clearly good enough for Linus.
I see why the project would prefer the decomposed parts to be available though - retitled the issue accordingly but won't be PR'ing it myself.

**Comment by qoomon** [comment]
I'll try to implementation git describe the same way as https://github.com/palantir/gradle-git-version.

I'd like to provide following placeholders
* `${describe}`
* `${describe.tag}`
* `${describe.tag.distance}`
* `${describe.PATTERN_GROUP}`

And following configuration
```xml
<branch>
  <pattern>master</pattern>
  <versionFormat>${describe}</versionFormat>
  <describeTagPattern>v(.*)</describeTagPattern>
<branch>
```

```xml
<branch>
  <pattern>master</pattern>
  <versionFormat>${describe}</versionFormat>
  <describe>
    <tagPattern>v(.*)</tagPattern>
    <lightTags>true</lightTags>
  </describe>
<branch>
```

Any naming or structure improvements you can think of?

WDYT?

**Comment by drekbour** [comment]
If `${describe}` is built from the individual parts then they should not be named `${describe.tag}` as they generic. If the parts are not computed but rather parsed _from_ `${describe}` then fine, they are indeed `${describe.tag}`.

`lightTags` -> `matchLightweightTags`

> (https://git-scm.com/docs/git-describe `--tags`) This option enables matching a lightweight (non-annotated) tag.

Docs to contain whichever is correct:
* "`${describe}` is shorthand for `${combined}${parts}` mimicking a call to `git describe`"
* "`${describe}` is the equivalent of a call to `git describe --args...`"

In the meantime, I am using the other plugin ;)

**Comment by afrimberger** [comment]
This feature is the missing piece to make the tag feature of the plugin usable. Therefore, I would love to see this feature implemented. Is there a chance to get it soon?

**Here is my use-case:**
For versioning, I'm tagging a commit with `v1.2.3-SNAPSHOT`. If I add another commit after the tag, the plugin falls back to the version from the pom.xml, which is in my case `0.0.1-SNAPSHOT`. However, I would expect that subsequent commits would be on the tagged version `1.2.3-SNAPSHOT`.

Or in other words, I expect the version to be `${describe.tag}`

**Comment by qoomon** [comment]
Hi @afrimberge there a 2 issues I have with this feature request
* 1# I don't like the idea of mutable versions. Generate version would change, if a tag is set before the current commit.
* 2# And the actual reason why this is not finished already are performance issues. I don't want to execute git describe if not necessary. And thats where I'm struggling, see my branch https://github.com/qoomon/maven-git-versioning-extension/tree/feature/git-describe

**Comment by qoomon** [comment]
So the main question is how to know if I need to execute git describe. git describe tag and distance should be available as placeholder and as property I think.

**Comment by qoomon** [comment]
A solution I could think of would be to execute and provide git describe placeholders and properties by setting an option at global or branch/tag level config. WDYT?

**Comment by afrimberger** [comment]
I see two use-cases:
1. Enable/disable describe on a _global level_, e.g. `<describeEnabled>true</describeEnabled>` (defaults to `false`).  There could be even a setting `<maxDescribeDepth>100</maxDescribeDepth>` for limiting the visited refs.
2. On a _branch level_ :

```xml
<branch>
  <pattern>master</pattern>
  <versionFormat>${describe}</versionFormat>
  <describe>
    <enabled>true</enabled>   <--- should be implicitly enabled if <describe> is specified
    <tagPattern>v(.*)</tagPattern>
  </describe>
<branch>
```

I don't think it makes sense to specify `<describe>` for tags, because if a tag matches, we're already on a tag. In that case it makes more sense to enable describe globally.

**Comment by qoomon** [comment]
what about this config?
```xml
<describe>
    <tagPattern>v(.*)</tagPattern>
    <depth>1000</depth>
 </describe>

<branch>
  <pattern>master</pattern>
  <versionFormat>${describe}</versionFormat>
  <describe>
    <tagPattern>v(.*)</tagPattern>
    <depth>1000</depth>
  </describe>
<branch>
```

**Comment by afrimberger** [comment]
I would rename `<depth>` to `<maxDepth>` to make it clear it is the maximum depth. But besides this small detail: LGTM :)

**Comment by qoomon** [comment]
One last thing, what behaviour you would expect if describe depth reaches max depth without a match?

**Comment by afrimberger** [comment]
I would expect an exception, because this is most likely an error the user needs to fix. For example, a CI/CD pipeline only clones the first 50 commits (e.g. Gitlab's default) and the tag is >=51 commits ahead.

**Comment by qoomon** [comment]
Sounds reasonable. Another situation just came to my mind, how to handle git describe before any tag was set e.g. initial project setup commits. Should we define some default tag ne like 'root' and distance to commits since initial commit?

**Comment by afrimberger** [comment]
I guess we should handle the initial case exactly as the case "max depth exceeded", because in a shallow cloned Git repo we can't distinguish between "intial" and "no tag found".

**Comment by qoomon** [comment]
basically it working. only thing left is to update config objects

**Comment by qoomon** [comment]
btw I was able to handle shallow repositories

**Comment by qoomon** [comment]
I think I will drop the option of max dept, because this option is not available for the `git describe` method.

**Comment by afrimberger** [comment]
awesome :)
the max depth option isn't necessary by all means. Thought it makes sense, because you had some performance concerns. But if the default is set to 1000, I guess we can even get rid of it completely.
Let me know if you have a testable state. I'm more than happy to try it out :)

**Comment by qoomon** [comment]
It's working, only thing that's missing is update the README accordingly.
Feel free to test the describe feature by checking out branch `feature/git-describe`, see CHANGELOG for some rudimentary documentation

**Comment by afrimberger** [comment]
**Test scenario**
I'm testing the _describeTagPattern_ feature with the following configuation:
```xml
<branch>
    <describeTagPattern>^v([0-9]+\.[0-9]+\.[0-9]+)$</describeTagPattern>
    <pattern>master</pattern>
    <versionFormat>${describe.tag}</versionFormat>
</branch>
```
The commit two commits before HEAD is tagged with `v0.0.7` and `v0.0.6-SNAPSHOT`. 

**Expected Result**
`v0.0.7`, because of the `describeTagPattern` regex

**Actual eesult**
`v0.0.6-SNAPSHOT`

**Why?**
The `tagPattern` is always set to `.*`, because `GitSituation` is instantiated in [line 169](https://github.com/qoomon/maven-git-versioning-extension/blob/418a0d2764b20a502f2121034cf78688ec4583b2/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L185) with a default `describeTagPattern`, but the actual value from the configuration is set in [line 185](https://github.com/qoomon/maven-git-versioning-extension/blob/418a0d2764b20a502f2121034cf78688ec4583b2/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L185). Through that, the GitSituation ctor always falls back to the describeTagPattern default `.*`. 

I get the expected result, when I add the following line in `GitVersioningModelProcessor.java:187` (and add the according setter):
```java
gitSituation.setDescribeTagPattern(describeTagPattern);
```

**Comment by qoomon** [comment]
I'll fix it tomorrow.

**Comment by qoomon** [comment]
I did some refactoring. Now all git commands are lazy. So there is no need to enable describe feature just use the `${describe}` placeholder and it will work. Can you try it again?

**Comment by afrimberger** [comment]
I'll test it tomorrow

**Comment by qoomon** [comment]
FYI I merged the feature branch into `master`

**Comment by afrimberger** [comment]
For my tests, I'm using the following (stripped down) config:

```xml
<tag>
    <describeTagPattern><![CDATA[^v(?<version>[0-9]+\.[0-9]+\.[0-9]+)$]]></describeTagPattern>
    <versionFormat>${describe.version}</versionFormat>
</tag>

<branch>
    <pattern>master</pattern>
    <describeTagPattern><![CDATA[^v(?<version>[0-9]+\.[0-9]+\.[0-9]+)$]]></describeTagPattern>
    <versionFormat>${describe.version}</versionFormat>
</branch>
```
The previous described issue works now! However, in my tests I stumbled upon the following issues:

**Issue 1:**  In detached head mode, the version from the pom.xml is used. 
For example, Gitlab checks out a MR build in detached head. But, HEAD doesn't necessarily point to a tagged commit. Instead of returning the pom version, I would expect the describe implementation to return the "last" tag matching the _describeTagPattern_. I already tried setting `tag.pattern` to the same value as `tag.describeTagPattern`. 
What would be the desired configuration for this scenario?

**Issue 2:** Tag pattern group index not supported for describe 
According to the `CHANGELOG.md`, pattern group indices are allowed: `${describe.<TAG_PATTERN_GROUP_NAME or TAG_PATTERN_GROUP_INDEX>}`. 

At least `${describe.1}` returns null. For now I'm using named tag patterns, which works flawlessly.

**Comment by qoomon** [comment]
@afrimberger thanks a lot, I'll try to fix the issues today

**Comment by qoomon** [comment]
@afrimberger regarding **Issue 1** you need to configure a commit config e.g.
```xml
<commit>
       <describeTagPattern><![CDATA[^v(?<version>[0-9]+\.[0-9]+\.[0-9]+)$]]></describeTagPattern>
      <versionFormat>${describe.version}</versionFormat>
 </commit>
```
this config is used when no tag or branch config is matching current head situation.

**Comment by qoomon** [comment]
@afrimberger **Issue 2** should be fixed

**Comment by qoomon** [comment]
@afrimberger I'll release a new version as soon as you can confirm it's working on your side.

**Comment by afrimberger** [comment]
@qoomon
*issue 1*: Indeed! I missed the commit config section. Looks good now, thanks! 🥳 
*issue 2*: LGTM

**Comment by qoomon** [comment]
Version `6.5.0` is released.
