### ISSUE TITLE
Cannot override property declared in a parent pom

### ISSUE THREAD

**Issue by dumitrubogdanmihai** [qoomon/maven-git-versioning-extension#109]
The property substitution mechanism works only for properties defined in the target pom. If a property is defined in a parent pom, it isn't substituted. In this case I would expect to generate a new property in the current pom, that would override the one from the parent pom.

**Comment by qoomon** [comment]
Hi @dumitrubogdanmihai currently only existing properties get updated. I did it that way to prevent creating new property entries. It's not that easy to know if this property exist in any of its parent poms. Thats why it's not implemented right now. However I got your point.

**Comment by nhrdl** [comment]
Encountered the exact same scenario that @dumitrubogdanmihai faced. For larger/multiple projects, version is defined in the parent pom and none of our 40 odd maven projects declare the version number. Is there any workaround for this?

**Comment by qoomon** [comment]
@nhrdl Ill try to find a solution these days. I'm not sure if I should add all modified properties and versions as field to the pom. WDYT will this lead to some problems?

**Comment by qoomon** [comment]
Could provide a simple sample project to reproduce your problems?

**Comment by nhrdl** [comment]
I'll create and upload a simple maven file in next few hours. However, as far as pom files are concerned, it's nothing special. We have one master pom that decides the version of the product. We have a bunch of application specific POMs that include other modules and do nothing else and modules poms are normal POM files. Since every one uses branches, chances of stepping on each other shoes increase with same version derived from master pom. Changing the version in pom file introduces unnecessary merge headaches and this extension will be perfect. I tried it on standalone project and worked perfectly, but on master repository, it did not work.

**Comment by qoomon** [comment]
I played around with some scenarios, however it works for me. If I run a `mvn` command in a sub module properties gets replaced as expected. Or do you look at the `pom.xml` file? I run following command `mvn help:evaluate -Dexpression=foo`
(`foo` is a property name)

`foo` property evaluates to configured value (`moin_moin`) although property is defined only at parent pom file.

`maven-git-versioning-extension.xml`
```xml
<configuration xmlns="https://github.com/qoomon/maven-git-versioning-extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://github.com/qoomon/maven-git-versioning-extension https://qoomon.github.io/maven-git-versioning-extension/configuration-6.4.0.xsd">
    <branch>
        <pattern>.*</pattern>
        <versionFormat>${version}</versionFormat>
        <property>
                 <name>foo</name>
                 <valueFormat>moin_moin</valueFormat>
        </property>
    </branch>

</configuration>
```

**Comment by qoomon** [comment]
@dumitrubogdanmihai have you been able to test my example config, if it suits your needs?

**Comment by qoomon** [comment]
@nhrdl do you still working on the example project?
