### ISSUE TITLE
Missing information on minimal Maven version

### ISSUE THREAD

**Issue by MarcinGil** [qoomon/maven-git-versioning-extension#79]
After the latest update I got
"[2020-07-21T13:04:46.785Z] [ERROR] Failed to execute goal me.qoomon:maven-git-versioning-extension:5.2.0:git-versioning (git-versioning) on project common: **The plugin me.qoomon:maven-git-versioning-extension:5.2.0 requires Maven version 3.6.3** -> [Help 1]"

Is it possible to include such information in Release notes?

**Comment by qoomon** [comment]
Hi @MarcinGil that is strange. I actually didn't bump tat version requirement by purpose.
I will check this

**Comment by qoomon** [comment]
Sorry for the inconvenience I set maven version requirement in the project pom.xml and I wasn't aware of the effect for the final extension. So it is because of this new line https://github.com/qoomon/maven-git-versioning-extension/blob/master/pom.xml#L5
Do you need a release with version requirement fix or are you able to update your maven installation?
I will add minimal maven version requirement to README.md as well

**Comment by MarcinGil** [comment]
Thanks, I'll update my installation - no problem. The issue popped up because we can't easily update maven on the CI infra we use. It of course "works for me" because I have always the latest versions on my workstation.

**Comment by qoomon** [comment]
glad to hear that.
