### ISSUE TITLE
Is there support for something to get highest --merged tag as a property?

### ISSUE THREAD

**Issue by jpierson** [qoomon/maven-git-versioning-extension#81]
I was hoping that there may be some concept to expose the highest version tag that has been merged into the current ref. The purpose would be to simulate what the semantic version would be for feature branches without having to resort to all of these branches using a symbolic default such as `0.0` or by using the feature name as shown in the default example in the README.md. The main use would be to give local builds a more familiar semantic version number that developers would recognize.

What I was thinking was something like grabbing the first result from a command such this:
```bash
git tag -l --sort -version:refname --merged
```

If my question/request isn't clear I can clarify with a diagram or better explanation.

**Comment by qoomon** [comment]
Currently this extension only works on current checkout commit without looking at commit history.
In my opinion Nobody knows in advance how the version needs to be adapted. Thats why I always use just `-SNAPSHOT` suffix.
However I may can add options for accessing git informations from prior commits.
Could you provide a simple graph that shows your expected behavior?
